create database db1;
use db1;
select database();
create table Details(id int primary key,ename varchar(20));
insert into Details values(201,'Sandhya');
insert into Details values(202,'Swathi');
insert into Details values(203,'archana');
select  * from Details;
alter table Details add age int ;
update Details set age=20 where id=203;
update Details set age=24 where id=202;
select * from Details order by age desc;
alter table Details drop sno;
desc Details;
select id from Details order by ename;
select * from Details where ename like '%a';
select * from Details where ename like 'a%';
select * from Details where ename like 's%';
select * from Details where ename like '__n%';
select * from Details where ename='Swathi' and age=34;
select * from Details where ename='Swathi' and age=24;
select distinct age from Details;
alter table Details add city varchar(20);
update Details set city='Hyderabad' where id=201;
update Details set city='Banglore' where id=202;
update Details set city='Chennai' where id=203;
select * from Details where city in('Hyderabad','Chennai');