create database Sandhya;
use Sandhya;
create table Employee(empid int primary key, empname varchar(20) not null, Salary int not null);
insert into Employee values(121,'Sandhya',20000);
insert into Employee values(122,'Sanjusha',50000);
insert into Employee values(123,'Varun',30000);
insert into Employee values(124,'Mansi',40000);
select * from Employee;
SHOW tables;
DESCRIBE Employee;
ALTER TABLE Employee ADD unique (empname);
select empname,Salary from Employee where empid=121;
update Employee set Salary=45000 where empid=124;
insert into Employee values(125,'Arpita',25000);
delete from Employee where empname='Arpita';
create table Department(deptid int primary key, deptname varchar(20), Empid int,foreign key(Empid) references Employee(Empid));
insert into Department values(1,'Technical',121);
insert into Department values(2,'Finance',122);
insert into Department values(3,'Technical',123);
insert into Department values(4,'HR',124);
select * from Department;
select * from Employee;
